### PR TITLE
Address nested object keys in ECS logging

### PR DESCRIPTION
**Pull request by untergeek**
Update Changelog.rst

### CODE REVIEW

**Comment by m1keil** [comment]
I would recommend using the `message` field instead of `log.original` in this case. 
> For log events the message field contains the log message, optimized for viewing in a log viewer.

While the `log.original`:
> This is the original log message and contains the full log message before splitting it up in multiple parts.
> 
> In contrast to the message field which can contain an extracted part of the log message, this field contains the original, full log message. It can have already some modifications applied like encoding or new lines removed to clean up the log message

Basically, you want to have `message` field, as it includes a human readable info about the event.

**Comment by untergeek** [comment]
Yes, the `WANTED_ATTRS` for `ECSFormatter` maps `message` to `log.original`. But if you follow [this code block](https://github.com/elastic/curator/pull/1531/files#diff-9b34ba2d4d832a313abb6c65555cda1fR62-R66) you'll find that if `message` is not in the `result` dictionary, it puts it there no matter what.

There is good reasoning to including both. `log.original` is not analyzed, and is only stored in `_source` (as you correctly indicated). But it is used by the Kibana Logs UI.

`message` is just the default message, and in ECS is mapped as `text` and `keyword`, both.

**Comment by untergeek** [comment]
Sample output:
```
{"@timestamp": "2020-03-13T22:39:38.041Z", "log": {"level": "INFO", "logger": "curator.cli", "origin": {"file": {"line": 226}, "function": "run"}, "original": "Job completed."}, "message": "Job completed."}
```
Note the presence of both `message` and `log.original` containing the same bits.

**Comment by m1keil** [comment]
gotcha, thanks for clarifying that!

**Pull request merged**
