### PR TITLE
Update Dockerfile to python:2.7.15-slim

### PR DESCRIPTION
**Pull request by SvenDowideit**
## Proposed Changes

  - update Dockerfile FROM line to current 2.7.15-slim base image.

I could also change it to `python:2.7-slim` so that it updates when there are patches...

### CODE REVIEW

**Comment by SvenDowideit** [comment]
I'd like to make it trivial for my developers to auto-expire indecies - is there any chance you guys can start shipping this image?

**Comment by untergeek** [comment]
Make it 3.6.5 and I might merge the changes.  We're not shipping an official image at this time, however.

**Comment by untergeek** [comment]
Also, `master` is behind the `5.x` branch.  You should commit against that branch.

**Comment by SvenDowideit** [comment]
closing - origin/5.x is already using more upto date stuff

**Pull request closed without merging**
