### PR TITLE
[WIP] Add support for AWS temporary security credentials.

### PR DESCRIPTION
**Pull request by mkubenka**

### CODE REVIEW

**Comment by untergeek** [comment]
If you'd be so kind as to add documentation for this, how it works, etc.  If you're not comfortable adding it to the [asciidoc files](https://github.com/elastic/curator/blob/v5.2.0/docs/asciidoc/configuration.asciidoc) yourself, please just document it here in a comment and I'll see about a commit to your branch.

**Comment by mkubenka** [comment]
Sure, I will try updating documentation with more info and examples.

**Comment by untergeek** [comment]
Any update on this?

**Comment by untergeek** [comment]
Also, how will this work in conjunction with the changes going into https://github.com/elastic/curator/pull/1012 ?

**Comment by mkubenka** [comment]
Sorry for delay, #1012 is better solution for AWS authentication.

I have added couple comments there with my suggestions. Closing this.

**Pull request closed without merging**
