### PR TITLE
raise exception when unable to create index

### PR DESCRIPTION
**Pull request by alexhornbake**
Fixes https://github.com/elastic/curator/issues/1525

## Proposed Changes

Raise an exception for an failure to create index, and report the cause of the exception

### CODE REVIEW

**Comment by alexhornbake** [comment]
hmmm.... I just signed the CLA. wondering if mentioning the cla-checker-service in a comment will trigger a new check.

**Comment by alexhornbake** [comment]
@untergeek any chance you could take a look at this PR, or help assign a reviewer? Much appreciated! 🙏

**Comment by untergeek** [comment]
Sorry for keeping you waiting. Development is no longer my day job, so I find myself struggling to find time to maintain and develop this. I remain the only maintainer of Curator, so that's the primary reason for the delays in updates. With COVID-19 changing so much of my routine, I've had even less time.

The nice thing is that I should begin to have more time to do this as a personal project on my own time, starting in evenings, soon. I hope to get a 5.9 release out before June, with security and bug fixes, primarily. This should make the cut.

**Comment by alexhornbake** [comment]
No worries. Take care and stay safe. Thank You!

**Pull request closed without merging**
