### PR TITLE
Raise elasticsearch-py version constrains

### LINKED ISSUE #1283: elasticsearch-curator fails to work with >=elasticsearch-py-5.5.2,<6.0.0
Hello,
elasticsearch-curator-5.5.4 fails to work with elasticsearch-py-5.5.2 (albeit it should according to https://github.com/elastic/curator/blob/master/setup.py#L25):
res = ['elasticsearch>=5.5.2,!=6.0.0,<7.0.0' ]

````
$ curator
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/curator", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3098, in <module>
    @_call_aside
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3082, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3111, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'elasticsearch!=6.0.0,<7.0.0,>=5.5.2' distribution was not found and is required by elasticsearch-curator
````

Since elasticsearch-py-5.5.2 the package was renamed from elasticsearch to elasticsearch5:
https://github.com/elastic/elasticsearch-py/commit/f20a73e3f36a54ba47530d8f53f5e3029fe20fcc

elasticsearch-py-6.0.0+ is named elasticsearch so it works with those versions.

Downstream issue: https://bugs.gentoo.org/667526

Thanks

### PR DESCRIPTION
**Pull request by hydrapolic**
Fixes #1283

### CODE REVIEW

**Comment by untergeek** [comment]
Due to #1279, the CI checks will not pass.  You can actually address both issues by changing `click>=6.7` to `click>=6.7,<7.0` in the same files.

**Comment by untergeek** [comment]
Which I understand if you don't want to add.  It's a catch-22 of sorts: The PR should only address one change, but it can't pass until either someone else merges that change and you rebase your PR, or you add both changes.

**Comment by untergeek** [comment]
Fantastic, thanks.

**Comment by hydrapolic** [comment]
Thank you :)

**Comment by sathishbalajir** [comment]
Hey Guys, I got to know the workaround to switch to 6.7 version. Just that I am curious, if there has there has not been a fix on this bug. I dont see there is fix for this issue in the upcoming Click 7.1 as well and we cant always switch back to 6.7 all the time for making things work as expected. Please help.

**Comment by untergeek** [comment]
@sathishbalajir No workarounds yet. If you're set on using `pip`, why not use a `virtualenv` where you can let it maintain its own module versions? Then there's no "switching back" to older versions of `click`.

```
$ pip install virtualenv
$ python -m virtualenv /path/to/curator_venv
$ source /path/to/curator_venv/bin/activate
[curator_venv] $ pip install elasticsearch-curator
```
Then, whenever you need to run curator, you do it to the virtualenv path:

```
/path/to/curator_venv/bin/curator
/path/to/curator_venv/bin/curator_cli
/path/to/curator_venv/bin/es_repo_mgr
```

**Pull request merged**
