### PR TITLE
#996: Added functionality to dynamically filter indices based on …

### PR DESCRIPTION
**Pull request by soenkeliebau**
…their age and a value that is taken from the index name with a regex.

### CODE REVIEW

**Comment by untergeek** [comment]
I won't be able to address this PR this week, unfortunately.  I'll be attending (and presenting at) OpenWest.  I'll get to this as soon as I otherwise can.

**Comment by soenkeliebau** [comment]
No worries, there really is no rush on this.
I'll see if I find some time to look at existing tests and try to come up with a few cases to test this functionality in the meantime.

**Comment by untergeek** [comment]
Sorry for the delay.  I started a review.  It looks good!  Only cosmetic issues, plus adding the API documentation.

All we need now are some tests, and we'll be good to go.

**Comment by untergeek** [comment]
Please be sure to rebase on the master branch.  I just released 5.1.2, and there are some changes.

**Comment by soenkeliebau** [comment]
I've rebased on master and added some integration tests for the filtering functionality as well as fixed two small things regarding error handling, when an illegal regex is given or it contains no capture group.
Do we also want to add unit tests? I was unsure because I'd have to add new cluster and index settings to the testvars and it seemed like duplication of what we already test with the integration tests to me. 
But I am of course happy to do that as well.

**Comment by untergeek** [comment]
If integration tests are handling it all, unit tests are redundant.  I tend to try to test as much as I can in unit tests, and then do some quick end-to-end tests, both positive and negative, in integration tests.  If you've added them all to integration, that's fine too, though.

I'll take another look and merge when done.

**Comment by untergeek** [comment]
Got burned by this test:
```
    def test_retention_from_name_illegal_regex_with_fallback(self):
        # Test extraction of unit_count from index name when pattern contains an illegal regular expression
        # Create indices for 10 months with retention time of 2 months in index name
        # Expected: Fallback value of 3 is used and 3 most recent indices remain in place
        self.args['prefix'] = 'logstash_2_'
        self.args['time_unit'] = 'months'
        self.create_indices(10)
        self.write_config(
            self.args['configfile'], testvars.client_config.format(host, port))
        self.write_config(self.args['actionfile'],
                          testvars.delete_pattern_proto.format(
                              'age', 'name', 'older', '\'%Y.%m\'', 'months', 3, '_[0-9+_', ' ', ' ', ' '
                          )
                          )
        test = clicktest.CliRunner()
        result = test.invoke(
            curator.cli,
            [
                '--config', self.args['configfile'],
                self.args['actionfile']
            ],
        )
        self.assertEquals(3, len(curator.get_indices(self.client)))
```

Works great, except that 3 months is not calculated as calendar months, but 3*30 days, which means that running this test today (at this time) will fail, as 90 days deletes the 3rd index (July), as UTC rollover is older than 6am on the 1st:

```
DEBUG      curator.indexlist          filter_by_age:457  Unit_count_pattern is set, trying to match pattern to index "logstash_2_2017.07"
DEBUG      curator.indexlist          filter_by_age:472  Unable to match pattern using fallback value of "3"
DEBUG      curator.indexlist           __actionable:35   Index logstash_2_2017.07 is actionable and remains in the list.
DEBUG      curator.indexlist            __excludify:58   Remains in actionable list: Index "logstash_2_2017.07" age (1498867200), direction: "older", point of reference, (1498932790)
```
Going to have to convert this test to a unit test with a fixed `epoch` as a result.

**Comment by untergeek** [comment]
Or...

Just not test months, but rather days, which don't suffer from that problem. 😄

**Comment by soenkeliebau** [comment]
thanks for catching and fixing this @untergeek !

Do you want me to add a test for months with fixed epoch also?

**Comment by untergeek** [comment]
I think the other tests are okay. Thanks, though!

**Pull request merged**
