### PR TITLE
Updated README - Broken Link

### PR DESCRIPTION
**Pull request by basex**
Getting Started Link was pointing to 404 page.

### CODE REVIEW

**Comment by basex** [comment]
I understand. I couldn't find the Getting Started page on the current path.

For me this pull request can be closed.

**Comment by untergeek** [comment]
If you change the link to the About page, it should be roughly the same info: https://www.elastic.co/guide/en/elasticsearch/client/curator/current/about.html

**Comment by untergeek** [comment]
And I'd be happy to merge that change.

**Comment by untergeek** [comment]
@basex, did you want to make those changes, or just close the PR?  Feel free to close it yourself if you don't want to make those changes.

**Comment by basex** [comment]
Sorry for the delay, corrected with your link.

**Pull request merged**
