### PR TITLE
Adding support for data_hot role on data_node detection

### LINKED ISSUE #1620: Shrink action incompatible with new data tier roles
### Expected Behavior
I am running the following shrink action:
```
actions:
  1:
    action: shrink
    description: >-
      Cooling daily managed indexes older than 3 months
    options:
      ignore_empty_list: True
      continue_if_exception: True
      #disable_action: True
      shrink_node: frovhelsdata-n01.talentsoft.cloud
      number_of_shards: 1
      shrink_suffix: '-shrink'
      post_allocation:
        allocation_type: include
        key: _tier_preference
        value: data_warm,data_hot
      wait_for_completion: True
      wait_for_rebalance: True
    filters:
   ...
```

I expect the shrink process to run on the frovhelsdata-n01.talentsoft.cloud data node.

### Actual Behavior
When using data tier roles instead of generic data, the shrink action is not able to find a valid data node. I get the following message for all my data nodes (set as data_hot or data_warm). shrink_node: DETERMINISTIC also fails.
```
2021-10-04 16:11:15,725 INFO      Skipping node "frovhelsdata-n01.talentsoft.cloud": non-data node
```

frovhelsdata-n01.talentsoft.cloud have the following role set : 
```
node.roles:
- data_hot
- data_content
- ingest
```

### Steps to Reproduce the Problem
Use shrink action on a cluster with no "generic" dedicated data nodes

### Specifications

  - Version: 5.8.4
  - Platform: Ubuntu 16.04
  - Subsystem:

## Context (Environment)
On new deployments, usage of new data tier (https://www.elastic.co/guide/en/elasticsearch/reference/7.x/data-tiers.html) seems to be the new standard.
Implementing these new data tiers in curator should enable shrink support for non ilm managed indexes.

## Detailed Description
Curator should allow data_hot (and maybe also data_warm) nodes for _data_node(self, node_id) in actions.py

### PR DESCRIPTION
**Pull request by gnobironts**
Fixes #1620 

## Proposed Changes
  - Added data_hot role to _data_node check function
  - I havn't added the data_warm role to the list as these nodes are less wanted/efficient to run shrink operations

### CODE REVIEW

**Comment by gnobironts** [comment]
> ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [bfa388f](https://github.com/elastic/curator/commit/bfa388fa7aeb1843061c57519b74310aeafe5693)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

Just signed the CLA. How can I trigger a new cla-check ?

**Comment by gnobironts** [comment]
> > ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [bfa388f](https://github.com/elastic/curator/commit/bfa388fa7aeb1843061c57519b74310aeafe5693)
> > Please, read and sign the above mentioned agreement if you want to contribute to this project
> 
> Just signed the CLA. How can I trigger a new cla-check ?

OK, I think I have the answer

**Comment by untergeek** [comment]
Thank you for this. I will also have to test this with 7.15 (both the ES version and the Python Client version) before merging.

**Comment by untergeek** [comment]
This PR will need to be reconsidered as node roles have changed for v8.  Possible node types where data can be indexed (excluding `data_cold` and `data_frozen` as they cannot index new data) include:
  - `data`
  - `data_content`
  - `data_hot`
  - `data_warm`

**Comment by untergeek** [comment]
Superseded by #1721 

Thank you for the suggestion, I have implemented the needed changes and given you credit in the Changeling.

**Pull request closed without merging**
