### PR TITLE
Fix to be compliant with AWS ES 5.1

### LINKED ISSUE #880: AWS Elasticsearch version 5.x support?
AWS just released their Elasticsearch service last week (https://aws.amazon.com/about-aws/whats-new/2017/01/elasticsearch-5-now-available-on-amazon-elasticsearch-service/).   It seems like curator works with AWS but version 4 doesn't appear to work with AWS ES v2.x, will version 4 support AWS ES v5.x?

### PR DESCRIPTION
**Pull request by wanix**
Fixes #880 

## Proposed Changes

  - change the source index settings if we don't have the awaited default source
  - tested with AWS ES versions 5.1, 5.3, 6.0

### CODE REVIEW

**Comment by untergeek** [comment]
Please rebase against the 5.x branch, and use that as the merge branch.

**Comment by untergeek** [comment]
This cannot be merged until 2 changes are made:

1. Change the merge base from `elastic:master` to `elastic:5.x`
2. Rebase your changes against the `5.x` branch.

These two changes will fix the build issues that are preventing it from working in Travis CI.

**Comment by untergeek** [comment]
I'm getting ready to release 5.5 soon.  If you want this change to be included, please expedite the requested changes.

**Comment by wanix** [comment]
Error rebasing my branch. I closed this one and created https://github.com/elastic/curator/pull/1172

**Pull request closed without merging**
