### PR TITLE
settings.role_arn is needed for snapshot registration

### PR DESCRIPTION
**Pull request by rodolfo-gonzalez**
{"Message":"settings.role_arn is needed for snapshot registration."}.

Fixes #

## Proposed Changes

  -
  -
  -

### CODE REVIEW

**Comment by ryanoolala** [comment]
I'm facing this issue as well. could this be merged? Or does anyone have other ways of creating repository with AWS ES?

**Comment by untergeek** [comment]
Please rebase your changes against the `master` branch. I'm sorry for the inconvenience.

**Comment by rodolfo-gonzalez** [comment]
@untergeek rebased

**Comment by MilanDasek** [comment]
Guys, what I need to do to make this working please?

I have copied utils.py from the commit to /usr/lib/python2.7/site-packages/curator/utils.py into my docker image, but when I call  
`es_repo_mgr --config /tmp/curator.yml create s3 --repository prod-$dt --bucket $bucket --region us-east-1 --base_path prod-$dt --role_arn arn:aws:iam:...`

I still get `Error: no such option: --role_arn`

Please advise.

Thank you

Milan

**Comment by MilanDasek** [comment]
Hello, any news here please?

**Pull request merged**
