### PR TITLE
Display proper error when mapping incorrect

### PR DESCRIPTION
**Pull request by namreg**
Fixes #
https://github.com/elastic/curator/issues/1525

### CODE REVIEW

**Comment by namreg** [comment]
> ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement):
> [6a76cce](https://github.com/elastic/curator/commit/6a76ccea45b3deb6a911d60cfd4091888f9db50f)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

signed

**Comment by untergeek** [comment]
Please rebase against the current master branch. I'll look into anything that comes up after that.

**Comment by namreg** [comment]
@unexpectedack done

**Comment by untergeek** [comment]
Two tests are not passing:

```
======================================================================

FAIL: test_already_existing_pass (test.integration.test_create_index.TestCLICreateIndex)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/elastic/curator/test/integration/test_create_index.py", line 138, in test_already_existing_pass

    self.assertEqual(0, result.exit_code)

AssertionError: 0 != 1
```
and
```
======================================================================

FAIL: test_incorrect_mapping_fail_with_propper_error (test.integration.test_create_index.TestCLICreateIndex)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/elastic/curator/test/integration/test_create_index.py", line 167, in test_incorrect_mapping_fail_with_propper_error

    self.assertTrue(b'mapper_parsing_exception' in result.output_bytes)

AssertionError: False is not true
```

**Comment by untergeek** [comment]
Hmmm. I'm not sure what happened here. This test should not fail based on what you added:

```
======================================================================

FAIL: test_delete_in_period_intersect (test.integration.test_delete_indices.TestActionFileDeleteIndices)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/elastic/curator/test/integration/test_delete_indices.py", line 361, in test_delete_in_period_intersect

    self.assertEqual(0, result.exit_code)

AssertionError: 0 != 1
```
My best guess is that the index doesn't have a proper value for a timestamp.

The way to fix it, I hope, is to add between the current lines 347 and 348 of [`test/integration/test_delete_indices.py`](https://github.com/elastic/curator/blob/master/test/integration/test_delete_indices.py):

```
self.client.indices.refresh(index='ilm-history-1-000001')
```

**Comment by untergeek** [comment]
This is only happening with Elasticsearch 7.6 (new default index appearing called `ilm-history-1-000001` whenever an index is created that _might_ be ILM affiliated).

**Comment by namreg** [comment]
@untergeek I've added a filter to skip `ilm-history-*` indices (the the latest commit). The same tests still failed, but now could not figured out what the cause of the fail.

**Comment by untergeek** [comment]
The filter you added to skip `ilm-history` indices should be first, before the other date filters. The problem is, if I guess correctly, the intersect tests being run against the `ilm-history` index, which your filter won't remove until after the intersect test (filters are processed in the order in which they appear).

**Comment by namreg** [comment]
@untergeek Seems, tests passed now. 
P.S. Sorry for the delay.

**Comment by untergeek** [comment]
Apologies for the nearly 4 year delay in merging this. It required a bit of adaptation to accomplish as the code base and many dependencies have changed. I can't merge it as-is, and I won't ask you to rebase this again, but you will be credited for your work here in the Changelog.

**Pull request closed without merging**
