### PR TITLE
Update examples.asciidoc

### PR DESCRIPTION
**Pull request by iz4blue**
fix running options

### CODE REVIEW

**Comment by untergeek** [comment]
Thanks for touching up the docs.  Could you please [sign the CLA](http://www.elasticsearch.org/contributor-agreement/), as this is a requirement for any code (or documentation) submission.

**Comment by untergeek** [comment]
@iz4blue any update here?

**Comment by iz4blue** [comment]
@untergeek sorry too late. i am reading CLA...

**Comment by untergeek** [comment]
@iz4blue I can't merge your changes without you signing the CLA.

**Pull request closed without merging**
