### PR TITLE
fixed regex filter documentation

### PR DESCRIPTION
**Pull request by arne-cl**
Fixes # documentation about regex filter

## Proposed Changes

  - change a word
  -
  -

### CODE REVIEW

**Comment by arne-cl** [comment]
I have signed the CLA now.

**Comment by untergeek** [comment]
Please change this to merge into `elastic:5.x` instead of master.

**Comment by arne-cl** [comment]
Dear @untergeek, I changed the merge branch as requested.

**Comment by untergeek** [comment]
Hmmm.  Can you rebase this against 5.x?  That's a bunch of other merges that don't need to happen in there.

**Comment by untergeek** [comment]
If it doesn't build cleanly, I can't merge it.  Can you rebase against `5.x` please?

**Comment by untergeek** [comment]
I just re-ran the CI tests, and the thing keeping this from being merged has been fixed, but you will need to rebase against the current `5.x` branch for that to work.  

How will you proceed?

**Comment by untergeek** [comment]
I'm releasing version 5.5 soon, and if you want this change included, please do the requested changes soon.

**Comment by arne-cl** [comment]
Sorry for the delay. This seems like an awful lot of work just to merge a one-word change
in the documentation.

**Comment by untergeek** [comment]
You are so right.  😞 

I apologize for the extra work.  I want you to get credit for the change.  Part of the problem was an unrelated error that prevent the CI tests from succeeding.  But your PR was still against the old code, so it still failed.  I probably should have merged it anyway, being a doc change only.

Thank you for persevering.

**Comment by arne-cl** [comment]
Dear Aaron,
I just saw that there is a `Allow edits from maintainers` checkbox for pull requests.
I guess this would have solved our problem, but I never noticed it before.

Best,
Arne

**Comment by untergeek** [comment]
I just noticed that box yesterday as well.  However, I think that the `Allow edits from maintainers` option does not allow me to rebase your original PR, just make edits to the branch.  This merge required a full rebase, unfortunately.

**Pull request merged**
