### PR TITLE
exclude option in build_filter api

### PR DESCRIPTION
**Pull request by zzugg**
no need 'exclude' argument in build_filter, because it is one of 'kindOf' argument in the code

### CODE REVIEW

**Comment by untergeek** [comment]
Thanks for this.  Can you rebase and add a blurb to the changelog and add yourself to the contributors list, please?

**Comment by untergeek** [comment]
@zzugg if you don't want to add yourself to the Contributors file, and update the Changelog, let me know.  I'll still merge your changes and add these myself.

**Comment by untergeek** [comment]
@zzugg I'll take care of it.  Thanks for the code change.

**Comment by zzugg** [comment]
@untergeek I am sorry for late response. Thank you for merging it.

**Pull request merged**
