### PR TITLE
Add option to wait_for_rebalance on shrink action

### PR DESCRIPTION
**Pull request by tschroeder-zendesk**
## Proposed Changes

  - Adds a new option `wait_for_rebalance` which defaults to True as this is the current behavior. This option uses a different function to check if an index is done being moved by finding the state of each shard rather than looking at the clusters relocating shard count. I run very large clusters and I don't have time to wait for a full rebalance between each shrink action. This code allows you to turn on this feature and have it use this new method of checking. I have been running this code for a couple days and it is working great. I tried to add what I could in regards to testing and I updated the docs. Let me know if anything else is required.

 - Removes spaces at the end of lines (minor formatting whitespace fixes)

 This may satisfy #1088

### CODE REVIEW

**Comment by untergeek** [comment]
This needs to be merged against the 5.x branch, rather than master.

**Comment by untergeek** [comment]
And possibly rebased against it first.

**Comment by tschroeder-zendesk** [comment]
Ok.. will update.

**Comment by tschroeder-zendesk** [comment]
Retargeted and rebased.

**Comment by untergeek** [comment]
Sorry for the delay.  I've been on vacation.

Please go ahead and make a 5.4.2 header and put this under it (for now).

**Comment by tschroeder-zendesk** [comment]
No worries. Updated.

**Comment by tschroeder-zendesk** [comment]
The two tests that failed appear to be travis issues can you re-run them?

**Pull request merged**
