### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by cachedout**
Filebeats -> Filebeat

Fixes typo in documentation

## Proposed Changes

  - Changes `Filebeats` to `Filebeat` in one line in the documentation

### CODE REVIEW

**Comment by cachedout** [comment]
Closed for lack of review response.

**Comment by untergeek** [comment]
I'm sorry you got caught in the middle of a release build issue. I have not touched any PRs as a result. It doesn't have to be closed. I'm just waiting to finish repairing the build system before merging any more PRs.

**Comment by cachedout** [comment]
@untergeek Ah, thanks for the update. Much appreciated!

**Comment by cachedout** [comment]
@untergeek I bumped this PR just to see if the build system was working. Looks like there are still some errors so I assume you're still working on it. :)

**Pull request closed without merging**
