### PR TITLE
Setup cx_Freeze to build binary packages

### PR DESCRIPTION
**Pull request by untergeek**
## Build a Windows MSI package
```python
python setup.py bdist_msi
```
This will build a Windows installer package in the `dist` subdirectory, which
will have a name like `elasticsearch-curator-3.4.0-win32.msi`.

## Build Linux or Windows binaries and put them in a compressed archive.
It will also supply the MD5 and SHA1 checksums for you:
```python
python setup.py build_exe
python binary_release.py
```
This will build binary packages for Linux or Windows, depending on
the operating system at run time.  The resultant output on Linux will look like:

```
Archive: curator-3.4.0-linux-x86_64.tar.gz
curator-3.4.0-linux-x86_64.tar.gz.md5.txt = <md5sum>
curator-3.4.0-linux-x86_64.tar.gz.sha1.txt = <sha1sum>
```

and the resultant output on Windows would look like:

```
Archive: curator-3.4.0-win32.zip
curator-3.4.0-win32.zip.md5.txt = <md5sum>
curator-3.4.0-win32.zip.sha1.txt = <sha1sum>
```

### CODE REVIEW

**Comment by larsf** [comment]
Hi, when I try to  run python setup.py build_exe it complains build_exe is an invalid command, using python-setuptools-0.9.8-4 and python 2.7.5 on curator 4.0.0a10 - why might that be?

**Comment by untergeek** [comment]
Is there more to the error message?

**Comment by untergeek** [comment]
Are you building on a Windows machine?

**Comment by larsf** [comment]
I am building on a linux machine. Here the output:

ython ./setup.py build_exe
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command ‘build_exe'

**Comment by untergeek** [comment]
You probably don't need the `./`.  I did a clean build with a fresh git clone of master on a brand new Ubuntu 16.04 box:

```
python setup.py build_exe
running build_exe
creating directory build/exe.linux-x86_64-2.7
copying /usr/local/lib/python2.7/dist-packages/cx_Freeze/bases/Console -> build/exe.linux-x86_64-2.7/curator
copying /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 -> build/exe.linux-x86_64-2.7/libpython2.7.so.1.0
writing zip file build/exe.linux-x86_64-2.7/lib/python27.zip

  Name                      File
  ----                      ----
m BUILD_CONSTANTS
m StringIO                  /usr/lib/python2.7/StringIO.py
... LOTS OF OUTPUT
... ENDS SUCCESSFULLY
```

I did have to hack and install cx_Freeze from source, as it wouldn't build from `pip`.  But it did build.  But the beta release of cx_Freeze 5.0 still has some bugs:

```
» cd build/exe.linux-x86_64-2.7/
buh@macbuntu1 (06:32 PM) ~/git/curator/build/exe.linux-x86_64-2.7
» ./curator --help
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cx_Freeze/initscripts/Console.py", line 7, in <module>
    import os
ImportError: No module named os
buh@macbuntu1 (06:32 PM) ~/git/curator/build/exe.linux-x86_64-2.7
» ls lib
python2.7  python27.zip
buh@macbuntu1 (06:32 PM) ~/git/curator/build/exe.linux-x86_64-2.7
» file curator
curator: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=8f1852d4de0f340b37478fc11e43746e01e3bed6, stripped
```

**Comment by larsf** [comment]
Hi,
Duh - I hadn’t checked to see if cx_Freeze was installed on the build machine.

Thanks for the eyeopener
Lars

**Comment by untergeek** [comment]
Can I close this now?

**Comment by untergeek** [comment]
Or you can 😄

**Comment by untergeek** [comment]
Never mind.  It's not an issue.

**Pull request merged**
