### PR TITLE
#1439: Modify prefix and suffix filter regex patterns to behave like substring matches, and abstract out duplicated code related to this change

### PR DESCRIPTION
**Pull request by Daniel314**
Hello,

This is my first pull request.  This pull request is for elastic/curator issue #1439.

The Curator documentation is not clear about 'prefix' and 'suffix' filters being regular-expression based
To me, the documentation seems to imply that prefix and suffix patterns are substring matches, so this pull request turns the prefix and suffix filters into substring matches.

This pull request makes the following changes:
   - Common pattern filter code in curator/snapshotlist.py and curator/indexlist.py has been coalesced and moved to curator/utils.py
   - The regex patterns in curator/defaults/settings.py have been moved to curator/utils.py (the regex_map() function has been removed)
   - The new code in curator/utils.py for the pattern prefix and suffix searches escapes regex characters so the regex pattern behaves like a substring search
   - Clarifies in docs/asciidoc/inc_kinds.asciidoc that 'prefix' and 'suffix' matches are substring matches

If these changes aren't satisfactory, please give me some ideas about changes that would be acceptable.

Regarding running 'python setup.py test':
  - In my development environment, I'm using ElasticSearch version 7.1.
    The official elactic/curator 'python setup.py test' XML summary output at the bottom reports quite a few failures (the total "Coverage" is 72%) -- I'm not sure what I need to adjust in my environment to get everything to pass...
    some of the errors are unicode vs non-unicode string mismatches; other errors are errors like "AssertionError: 0 != 5".
  - I've run 'python setup.py test' on the modifications in this pull request, and the test_... lines at the top of the output are identical to that of the official elactic/curator 'python setup.py test' output on my system.
    Said another way: The tests that pass for the official code still pass with my changes.
  - The XML failure summary for my repo doesn't match the XML failure summary for the official elactic/curator repo (in my development environment) for the four python files that I've modified, but the results are similar.

  -  As such, someone with a full working development environment should re-run 'python setup.py test' to validate my changes.

Thank you,

 Daniel

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @Daniel314, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/curator/pull/1443.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by Daniel314** [comment]
I've gone through the Contributor Agreement process twice now, and I'm still seeing a CLA signature missing error.  What else am I missing besides hopping through the DocuSign form process?

**Comment by Daniel314** [comment]
@elasticcla : What e-mail address do you see my commit coming from?  I only have one e-mail address associated with my Github account.

**Comment by Daniel314** [comment]
Okay, I believe I've submitted the CLA with the "correct" e-mail address now.

**Comment by untergeek** [comment]
> The official elactic/curator 'python setup.py test' XML summary output at the bottom reports quite a few failures (the total "Coverage" is 72%) -- I'm not sure what I need to adjust in my environment to get everything to pass...
some of the errors are unicode vs non-unicode string mismatches; other errors are errors like "AssertionError: 0 != 5".

See [here](https://github.com/elastic/curator/blob/v5.7.6/travis-run.sh#L49-L74) for some of the node-specific settings required for testing. There will still be 4 skipped tests when testing against a single cluster (remote reindex won't be tested, but skipped).  These are fully tested in CI.

Regarding the code changes, I like and appreciate what you have added, but this may break functionality for users who have been relying on `prefix` and `suffix` being regular expressions. Keeping with the principle of least surprise, I will have to release this change with a major version upgrade, with warnings/notifications to users that this is how it works.

**Comment by untergeek** [comment]
As an example, here is a semi-sanitized version of my testing `elasticsearch.yml` file:

```
cluster.name: foo
node.name: bar
path.repo: ["/", "C:\\" ]
reindex.remote.whitelist: esclient:9200, localhost:9200, 10.11.12.*:9200, localhost:9201
node.ingest: false
xpack.monitoring.enabled: false
node.ml: false
xpack.security.enabled: false
xpack.watcher.enabled: false
```

**Comment by untergeek** [comment]
Also,

### Coverage: 97%
Module | statements | missing | excluded | coverage
-- | -- | -- | -- | --
Total | 3270 | 112 | 0 | 97%
curator/__init__.py | 11 | 0 | 0 | 100%
curator/_version.py | 1 | 0 | 0 | 100%
curator/actions.py | 949 | 24 | 0 | 97%
curator/cli.py | 136 | 2 | 0 | 99%
curator/config_utils.py | 38 | 1 | 0 | 97%
curator/defaults/__init__.py | 0 | 0 | 0 | 100%
curator/defaults/client_defaults.py | 6 | 0 | 0 | 100%
curator/defaults/filter_elements.py | 83 | 0 | 0 | 100%
curator/defaults/filtertypes.py | 66 | 2 | 0 | 97%
curator/defaults/option_defaults.py | 158 | 0 | 0 | 100%
curator/defaults/settings.py | 33 | 0 | 0 | 100%
curator/exceptions.py | 13 | 0 | 0 | 100%
curator/indexlist.py | 510 | 28 | 0 | 95%
curator/logtools.py | 36 | 0 | 0 | 100%
curator/repomgrcli.py | 80 | 1 | 0 | 99%
curator/snapshotlist.py | 199 | 0 | 0 | 100%
curator/utils.py | 840 | 54 | 0 | 94%
curator/validators/__init__.py | 1 | 0 | 0 | 100%
curator/validators/actions.py | 20 | 0 | 0 | 100%
curator/validators/config_file.py | 4 | 0 | 0 | 100%
curator/validators/filters.py | 32 | 0 | 0 | 100%
curator/validators/options.py | 13 | 0 | 0 | 100%
curator/validators/schemacheck.py | 41 | 0 | 0 | 100%

**Comment by bryder** [comment]
This would be a breaking change which will break all of my curator configs. 

Ideally the docs would say they are regex's not substrings. 

I was also confused by the docs - I was working through someone else's curator config and was surprised to see regex's in the prefix patterns. 

I found the issue for the PR and discovered they are regexes.

**Comment by untergeek** [comment]
> Ideally the docs would say they are regex's not substrings.

This was addressed in #1558 via some asciidoc notes, e.g.

> NOTE: Internally _regex_ pattern is constructed from prefix value as `^{0}.*$`. Special characters should be escaped with backslash to match literally.
> NOTE: Internally _regex_ pattern is constructed from suffix value as `^.*{0}$`. Specials character should be escaped with backslash to match literally.

You can see that it's merged into the 8.0 docs [here](https://github.com/elastic/curator/blob/8.0/docs/asciidoc/inc_kinds.asciidoc). It will be a few hours before it shows up in the main documentation.

I agree with @bryder here. If switching to substring matching is going to break things for people, then I can't make a breaking change like that. Informing people that it is regex based should suffice. There's simply too much history here to arbitrarily change it now.

**Pull request closed without merging**
