### PR TITLE
Add a restore action to curator_cli

### PR DESCRIPTION
**Pull request by alexef**
- same options as snapshot supported, plus rename_pattern and rename_replacement
- tested against elasticsearch 5x

part of #851

### CODE REVIEW

**Comment by untergeek** [comment]
You might need to rebase this against master and make a few changes.  You've got a new feature under 5.1.2 in the Changelog, when this is something which won't make it until 5.3.  You may even need to add a new block to the head of Changelog.

**Comment by untergeek** [comment]
Any update on this?  I can't merge this with the new feature under the changelog for 5.1.2...

**Comment by alexef** [comment]
Was stuck with other work, will update it asap.

**Comment by alexef** [comment]
Rebased against master, added the changelog under 5.3.0.

I'm a bit confused, there are two Changelog files, one in the root, another one under docs/. Should I update both @untergeek ?

**Comment by untergeek** [comment]
Go ahead and do the one in `docs/`.  The other is a symlink.  I'll fix it if I have to.

**Comment by untergeek** [comment]
Oh, you already did.  No worries, then.

**Comment by arpit1305** [comment]
Hello all, 
is restore in curator_cli available in any of curator version?

**Comment by untergeek** [comment]
@arpit1305, it's just not documented:

## Clean install
```
$ curator_cli --version
curator_cli, version 5.8.3
```
## Followed by:
```
$ curator_cli --help
Usage: curator_cli [OPTIONS] COMMAND [ARGS]...

  CLI input

Options:
  --config PATH       Path to configuration file. Default: ~/.curator/curator.yml
  --host TEXT         Elasticsearch host.
  --url_prefix TEXT   Elasticsearch http url prefix.
  --port TEXT         Elasticsearch port.
  --use_ssl           Connect to Elasticsearch through SSL.
  --certificate TEXT  Path to certificate to use for SSL validation.
  --client-cert TEXT  Path to file containing SSL certificate for client auth.
  --client-key TEXT   Path to file containing SSL key for client auth.
  --ssl-no-validate   Do not validate SSL certificate
  --http_auth TEXT    Use Basic Authentication ex: user:pass -- DEPRECATED. Use username and password.
  --username TEXT     HTTP Basic Authentication username
  --password TEXT     HTTP Basic Authentication password
  --timeout INTEGER   Connection timeout in seconds.
  --master-only       Only operate on elected master node.
  --dry-run           Do not perform any changes.
  --loglevel TEXT     Log level
  --logfile TEXT      log file
  --logformat TEXT    Log output format [default|logstash|json|ecs].
  --version           Show the version and exit.
  --help              Show this message and exit.

Commands:
  alias             Add/Remove Indices to/from Alias
  allocation        Shard Routing Allocation
  close             Close Indices
  delete_indices    Delete Indices
  delete_snapshots  Delete Snapshots
  forcemerge        forceMerge Indices (reduce segment count)
  freeze            Freeze Indices
  open              Open Indices
  replicas          Change Replica Count
  restore           Restore Indices
  rollover          Rollover Index associated with Alias
  show_indices      Show Indices
  show_snapshots    Show Snapshots
  shrink            Shrink Indices to --number_of_shards
  snapshot          Snapshot Indices
  unfreeze          Unfreeze Indices
```
## And specifically this:
```
curator_cli restore --help
Usage: curator_cli restore [OPTIONS]

  Restore Indices

Options:
  --repository TEXT               Snapshot repository  [required]
  --name TEXT                     Snapshot name
  --index TEXT                    Index name to restore. (Can invoke repeatedly for multiple indices)
  --rename_pattern TEXT           Rename pattern
  --rename_replacement TEXT       Rename replacement
  --extra_settings TEXT           JSON version of extra_settings (see documentation)
  --include_aliases               Include aliases with restored indices.  [default: False]
  --ignore_unavailable            Ignore unavailable shards/indices.  [default: False]
  --include_global_state          Restore cluster global state with snapshot.  [default: False]
  --partial                       Restore partial data (from snapshot taken with --partial).  [default: False]
  --wait_for_completion / --no-wait_for_completion
                                  Wait for the snapshot to complete  [default: True]
  --wait_interval INTEGER         Seconds to wait between completion checks.
  --max_wait INTEGER              Maximum number of seconds to wait_for_completion
  --skip_repo_fs_check            Skip repository filesystem access validation.  [default: False]
  --ignore_empty_list             Do not raise exception if there are no actionable indices
  --allow_ilm_indices / --no-allow_ilm_indices
                                  Allow Curator to operate on Index Lifecycle Management monitored indices.  [default: False]
  --filter_list TEXT              JSON array of filters selecting snapshots to act on.  [required]
  --help                          Show this message and exit.
```

**Pull request merged**
