### PR TITLE
Update command-line.asciidoc

### PR DESCRIPTION
**Pull request by zafarella**
## Proposed Changes
- add reference to curator_cli

### CODE REVIEW

**Comment by untergeek** [comment]
I'm sorry, I just don't see this as a necessary addition to this page.  The breadcrumb at the top refers to that page, and the sidebar does too.

**Comment by zafarella** [comment]
true, just saw it, but frankly you cannot notice it until you actually search deeply.

I was looking into the way listing snapshots and this is how came to this page.

Mbe add it as "Info" or "Tip" section?

**Comment by untergeek** [comment]
The exit codes refer to both the `curator` and `curator_cli` binaries.  It shouldn't need more than that, really.

**Comment by zafarella** [comment]
I think this is what I meant https://github.com/elastic/curator/pull/1273
Sorry for confusing, not much familiar with ascidocs yet

**Pull request closed without merging**
