### PR TITLE
Fixing day of year regular expression

### PR DESCRIPTION
**Pull request by petitout**
Currently, the regular expression for day of year is {3}.
It implies that day of year should contain 3 digits.
This modification allows the day of year to contain from 1 to 3 digits. 
Examples :
indiceName-2015-1
indiceName-2015-65
indiceName-2015-365

### CODE REVIEW

**Comment by petitout** [comment]
I updated the test case and ran "run_tests.py"

**Comment by untergeek** [comment]
Thanks for catching this!  Don't know why I didn't think of it when I merged the original PR, but clearly there aren't many people using this or I'd have heard about it sooner (or they just didn't check until today :smile: )

Can you please:

1. Sign the CLA
2. Update the Contributors file
3. Update the Changelog with a brief synopsis of what you've done (under Bug Fixes)

If you sign the CLA before merging other commits, it should pick up the change then.  If not, I can manually verify.

**Comment by petitout** [comment]
You're welcome !
Thanks for your work

I've done all you wanted.
I've signed the CLA after creating the pull request and before pushing the
latest commit.
However, the CLA state didn't change

Thanks

Julien

**Comment by untergeek** [comment]
Very strange.  I wonder why it doesn't recognize you. A manual CLA check says you signed the CLA on 2015-06-09.  Did you commit to a different Elastic repository last year?  Did you change the email address associated with your Github account by chance?

**Comment by petitout** [comment]
No I didn't .
I signed it again today using :
Name : julien mancuso
Github login : petitout
Email : petitout@gmail.com

**Comment by untergeek** [comment]
No worries.  Must be something up with our CLA checker.

**Pull request merged**
