### PR TITLE
Fix warnings in Python 3.8

### LINKED ISSUE #1511: Deprecation warning and syntax warning in Python 3.8
## To submit a bug or report an issue

Deprecation warnings are raised due to invalid escape sequences in Python 3.8 . Below is a log of the warnings raised during compiling all the python files. Using raw strings or escaping them will fix this issue.

```
find . -iname '*.py'  | xargs -P 4 -I{} python -Wall -m py_compile {}

./test/integration/test_count_pattern.py:52: DeprecationWarning: invalid escape sequence \d
  '\'^(a|b|c)-\d$\'', 'false', 'name', '\'%Y.%m.%d\'', 'true', 1
./test/integration/test_count_pattern.py:78: DeprecationWarning: invalid escape sequence \d
  '\'^(a|b)-\d{4}\.\d{2}\.\d{2}$\'', 'true', 'name', '\'%Y.%m.%d\'', 'true', 1
./curator/indexlist.py:882: DeprecationWarning: invalid escape sequence \d
  """
./curator/actions.py:151: SyntaxWarning: "is" with a literal. Did you mean "=="?
  'to' if job is 'add' else 'from',
```

### PR DESCRIPTION
**Pull request by tirkarthi**
Fixes #1511 

## Proposed Changes

* Fix deprecation warnings over invalid escape sequences using raw strings
* Fix syntax warning over using is for literal comparison with ==

### CODE REVIEW

**Comment by tirkarthi** [comment]
CLA has been signed

**Comment by untergeek** [comment]
Please rebase against the current master branch. I'll look into anything that comes up after that.

**Comment by tirkarthi** [comment]
@untergeek Rebased. Thanks.

**Comment by untergeek** [comment]
Multiple tests are failing:

```
======================================================================
FAIL: test_match_proper_indices (test.integration.test_count_pattern.TestCLICountPattern)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/elastic/curator/test/integration/test_count_pattern.py", line 64, in test_match_proper_indices
    self.assertEquals(['a-3', 'b-6', 'c-8', 'not_a_match'], indices)
AssertionError: Lists differ: ['a-3', 'b-6', 'c-8', 'not_a_m... != [u'a-1', u'a-2', u'a-3', u'b-4...

First differing element 0:
'a-3'
u'a-1'

Second list contains 7 additional elements.
First extra element 4:
u'b-5'

- ['a-3', 'b-6', 'c-8', 'not_a_match']
+ [u'a-1',
+  u'a-2',
+  u'a-3',
+  u'b-4',
+  u'b-5',
+  u'b-6',
+  u'c-5',
+  u'c-6',
+  u'c-7',
+  u'c-8',
+  u'not_a_match']
```

In each that I have looked at, it seems that the results might need to be sorted to be properly compared. This was not the case before your code changes. Clearly, this can be coded around, but it does require extra changes to code, somewhere.

**Comment by untergeek** [comment]
This is moot now that Curator is 3.8+ only and has likely addressed the original issue.

**Pull request closed without merging**
