### PR TITLE
Implementing the enhancement #392 : it is now possible to specify the …

### PR DESCRIPTION
**Pull request by petitout**
…day of the year in the filter

### CODE REVIEW

**Comment by untergeek** [comment]
Have you signed the [CLA](http://www.elasticsearch.org/contributor-agreement/)?  I can merge this after you've signed.

**Comment by petitout** [comment]
Yep just did it :-)
Thanks
Le 9 juin 2015 15:57, "Aaron Mildenstein" <notifications@github.com> a
écrit :

**Comment by petitout** [comment]
I've signed the CLA but always mentioning I have not ...
is there anything special to do ?

**Comment by untergeek** [comment]
For this PR it won't show up.  If you submit to any Elastic owned repository in the future, it will show as signed.

**Comment by untergeek** [comment]
lgtm!

**Pull request merged**
