### PR TITLE
Add forward compatible support for click 7.0

### PR DESCRIPTION
**Pull request by rectalogic**
click changed command names to use dashes instead of underscores, so force the underscore name to be used to maintain backward compatibility.
https://github.com/pallets/click/issues/1123#event-1869555443

Handle changed click exit_code
https://github.com/pallets/click/pull/533

### CODE REVIEW

**Comment by untergeek** [comment]
Thank you for this, but I have no intention of allowing click 7.0 before the next major release of Curator. I will revisit all flags then, as the major release version will allow me to make breaking changes. 

I will probably standardize on hyphens at that point, instead of underscores.

**Comment by untergeek** [comment]
I am on my phone right now, but it looks like all CI tests failed. I will take a look at “why” later.

**Comment by untergeek** [comment]
Curator 5.6.0 pins the click version to disallow 7.0, in case you didn’t see that change.

**Comment by rectalogic** [comment]
This PR makes curator compatible with both click 6.x and 7.x with no breaking changes in curator. I think the failing tests are tests that were skipped when I ran tests (all tests pass for me with both click 6.7 and 7.0, but 4 tests were skipped for some reason). I'll push a change that should fix these failures.

It looked to me like curator disallowed 7.0 because 7.0 has breaking changes, so fixing curator to be compatible with both click 6.x and 7.x seemed like an alternative to forcing an older version of click.

**Comment by rectalogic** [comment]
I don't know why travis is failing now. The only error I see is related to downloading jdk:
```
Downloading Oracle Java 8...
--2018-11-29 22:06:59--  http://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-x64.tar.gz
Resolving build-cache.travisci.net (build-cache.travisci.net)... 10.80.1.2
Connecting to build-cache.travisci.net (build-cache.travisci.net)|10.80.1.2|:80... connected.
Proxy request sent, awaiting response... 302 Moved Temporarily
Location: https://edelivery.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-x64.tar.gz [following]
--2018-11-29 22:06:59--  https://edelivery.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-x64.tar.gz
Resolving false (false)... failed: Name or service not known.
wget: unable to resolve host address ‘false’
download failed
Oracle JDK 8 is NOT installed.
dpkg: error processing package oracle-java8-installer (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 oracle-java8-installer
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command "sudo apt-get update && sudo apt-get install oracle-java8-installer" exited with 100.
```

**Comment by untergeek** [comment]
Again, I appreciate the effort, but there is no compelling need to upgrade to click 7.0. There is no new feature in it that Curator requires. Quite the contrary, the default hyphen/underscore behavior is a reason to avoid it, even if a reasonable work-around can be made for it. 6.7 is just fine for what Curator needs.

I do plan on making major changes for Curator 6.0, and will pin click at `>=7.0` for that release, and make appropriate changes to the command-line flags as needed.

**Comment by hydrapolic** [comment]
Having curator working with click 6/7 would be greatly appreciated on rolling distros like Gentoo. Currently we have a strict restriction on <click-7. This means that even though all other packages on the system can work with click 7, only curator is blocking the upgrade and forcing 6. If it's too much work I understand, but if curator could be compatible with both, it would be really great.

**Comment by hydrapolic** [comment]
Any chance adding click 7 support please? In Gentoo Linux, curator is one of the last packages requiring <click-7.

**Comment by untergeek** [comment]
This is already moot as Click 8.1.2 is supported.

**Pull request closed without merging**
