### PR TITLE
Fix newer-than flag description

### PR DESCRIPTION
**Pull request by ferki**
Just a quick doc fix :)

### CODE REVIEW

**Comment by untergeek** [comment]
Thanks for catching the cut/paste error!

Please be sure to sign the CLA as mentioned in the README.

**Comment by ferki** [comment]
I'm already a contributor through our company CLA ^^ Looks like the automatic tests still refuse to recognize this :(

**Comment by untergeek** [comment]
No problem. I can fix that now.

**Comment by ferki** [comment]
Thanks! \o/

**Comment by untergeek** [comment]
Manually added your name.  Future pull requests should not fail the CLA.

**Pull request merged**
